services:
  db:
    image: postgres:16-alpine
    container_name: futboldb_pg
    environment:
      POSTGRES_DB: futboldb
      POSTGRES_USER: futboldb
      POSTGRES_PASSWORD: futboldb
    ports:
      - "5433:5432"

    volumes:
      - futboldb_pg_data:/var/lib/postgresql/data

volumes:
  futboldb_pg_data:
